// This file is generated by ttrpc-compiler 0.2.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone)]
pub struct MyServiceClient {
    client: ::ttrpc::Client,
}

impl MyServiceClient {
    pub fn new(client: ::ttrpc::Client) -> Self {
        MyServiceClient {
            client: client,
        }
    }

    pub fn say_hello(&self, req: &super::service::HelloRequest, timeout_nano: i64) -> ::ttrpc::Result<super::service::HelloReply> {
        let mut cres = super::service::HelloReply::new();
        ::ttrpc::client_request!(self, req, timeout_nano, "service.MyService", "SayHello", cres);
        Ok(cres)
    }

    pub fn shutdown(&self, req: &super::service::ShutdownRequest, timeout_nano: i64) -> ::ttrpc::Result<super::service::ShutdownReply> {
        let mut cres = super::service::ShutdownReply::new();
        ::ttrpc::client_request!(self, req, timeout_nano, "service.MyService", "Shutdown", cres);
        Ok(cres)
    }
}

struct SayHelloMethod {
    service: Arc<std::boxed::Box<dyn MyService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for SayHelloMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, service, HelloRequest, say_hello);
        Ok(())
    }
}

struct ShutdownMethod {
    service: Arc<std::boxed::Box<dyn MyService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ShutdownMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, service, ShutdownRequest, shutdown);
        Ok(())
    }
}

pub trait MyService {
    fn say_hello(&self, _ctx: &::ttrpc::TtrpcContext, _req: super::service::HelloRequest) -> ::ttrpc::Result<super::service::HelloReply> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/service.MyService/SayHello is not supported".to_string())))
    }
    fn shutdown(&self, _ctx: &::ttrpc::TtrpcContext, _req: super::service::ShutdownRequest) -> ::ttrpc::Result<super::service::ShutdownReply> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/service.MyService/Shutdown is not supported".to_string())))
    }
}

pub fn create_my_service(service: Arc<std::boxed::Box<dyn MyService + Send + Sync>>) -> HashMap <String, Box<dyn ::ttrpc::MethodHandler + Send + Sync>> {
    let mut methods = HashMap::new();

    methods.insert("/service.MyService/SayHello".to_string(),
                    std::boxed::Box::new(SayHelloMethod{service: service.clone()}) as std::boxed::Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/service.MyService/Shutdown".to_string(),
                    std::boxed::Box::new(ShutdownMethod{service: service.clone()}) as std::boxed::Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods
}
